public enum SahhaSensor: String, CaseIterable, Codable, Sendable {
    case activity_summary
    case active_energy_burned
    case basal_body_temperature
    case basal_energy_burned
    case basal_metabolic_rate
    case blood_glucose
    case blood_pressure_diastolic
    case blood_pressure_systolic
    case body_fat
    case body_mass_index
    case body_temperature
    case body_water_mass
    case bone_mass
    case date_of_birth
    case device_lock
    case energy_consumed
    case exercise
    case exercise_time
    case floors_climbed
    case gender
    case heart_rate
    case heart_rate_variability_rmssd
    case heart_rate_variability_sdnn
    case height
    case lean_body_mass
    case move_time
    case oxygen_saturation
    case resting_heart_rate
    case respiratory_rate
    case running_ground_contact_time
    case running_power
    case running_speed
    case running_stride_length
    case running_vertical_oscillation
    case six_minute_walk_test_distance
    case sleep
    case sleeping_wrist_temperature
    case stand_time
    case stair_ascent_speed
    case stair_descent_speed
    case steps
    case time_in_daylight
    case total_energy_burned
    case vo2_max
    case waist_circumference
    case walking_asymmetry_percentage
    case walking_double_support_percentage
    case walking_heart_rate_average
    case walking_speed
    case walking_steadiness
    case walking_step_length
    case weight
}
